/**
 * Mã quyền dùng ở FE — phải khớp từng chữ với PermissionCatalog.java bên backend.
 * Danh sách quyền của người đang đăng nhập lấy từ /api/auth/me (AuthContext.permissions).
 */
export const PERMISSIONS = {
  USER_MANAGE: 'USER:MANAGE',
  ROLE_MANAGE: 'ROLE:MANAGE',

  EXAM_TYPE_MANAGE: 'EXAM_TYPE:MANAGE',
  EXAM_TYPE_LAYOUT_MANAGE: 'EXAM_TYPE:LAYOUT',
  EXAM_CATEGORY_MANAGE: 'EXAM_CATEGORY:MANAGE',
  EXAM_PART_MANAGE: 'EXAM_PART:MANAGE',
  SKILL_MANAGE: 'SKILL:MANAGE',
  TAG_MANAGE: 'TAG:MANAGE',
  SCORING_CONVERSION_MANAGE: 'SCORING_CONVERSION:MANAGE',
  QUESTION_COLLECTION_MANAGE: 'QUESTION_COLLECTION:MANAGE',
  MILESTONE_MANAGE: 'MILESTONE:MANAGE',
  RECOVERY_RESOURCE_MANAGE: 'RECOVERY_RESOURCE:MANAGE',

  TEST_MANAGE: 'TEST:MANAGE',
  EVALUATION_MANAGE: 'EVALUATION:MANAGE',

  POST_MODERATE: 'POST:MODERATE',
  POST_CATEGORY_MANAGE: 'POST_CATEGORY:MANAGE',

  CERTIFICATE_MANAGE: 'CERTIFICATE:MANAGE',

  QUEST_MANAGE: 'QUEST:MANAGE',
  COSMETIC_MANAGE: 'COSMETIC:MANAGE',
  COIN_MANAGE: 'COIN:MANAGE',
  STREAK_CONFIG_MANAGE: 'STREAK_CONFIG:MANAGE',

  AUDIT_VIEW: 'AUDIT:VIEW',
  DASHBOARD_VIEW: 'DASHBOARD:VIEW',
  EMAIL_MANAGE: 'EMAIL:MANAGE',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
