export enum QuestionType {
  MCQ = 'MCQ',
  MSQ = 'MSQ',
  FILL_BLANK = 'FILL_BLANK',
  ESSAY = 'ESSAY',
}

export enum PassageType {
  READING = 'READING',
  LISTENING = 'LISTENING',
}

export enum MediaType {
  IMAGE = 'IMAGE',
  AUDIO = 'AUDIO',
  DOCUMENT = 'DOCUMENT',
  TEXT = 'TEXT',
}

export enum TestStatus {
  NOT_STARTED = 'NOT_STARTED',
  OPEN = 'OPEN',
  ENDED = 'ENDED',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
}

export enum UserTestStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
}

export enum UserTestMode {
  FULL_TEST = 'FULL_TEST',
  PRACTICE = 'PRACTICE',
}

export enum LearningPlanStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REPLACED = 'REPLACED',
}

export enum PlanStage {
  FOUNDATION = 'FOUNDATION',
  MOCK = 'MOCK',
}

export enum PlanTaskType {
  TAG = 'TAG',
  PART_CAPSTONE_1 = 'PART_CAPSTONE_1',
  PART_CAPSTONE_2 = 'PART_CAPSTONE_2',
}

export enum TaskStatus {
  LOCKED = 'LOCKED',
  ACTIVE = 'ACTIVE',
  PASSED = 'PASSED',
  SKIPPED = 'SKIPPED',
}

export enum SessionStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
}

export enum CertificateStatus {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
}

export enum AttemptCertificateState {
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  JUST_ISSUED = 'JUST_ISSUED',
  ALREADY_OWNED = 'ALREADY_OWNED',
  NOT_PASSED = 'NOT_PASSED',
}

export enum CertificateVerifyState {
  VALID = 'VALID',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
  NOT_FOUND = 'NOT_FOUND',
}

export enum ClassMemberStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
}

export enum CosmeticType {
  FRAME = 'FRAME',
  BADGE = 'BADGE',
}

export enum QuestConditionType {
  NONE = 'NONE',
  COMPLETE_TEST = 'COMPLETE_TEST',
  STREAK_DAYS = 'STREAK_DAYS',
  CREATE_LEARNING_PLAN = 'CREATE_LEARNING_PLAN',
  COMPLETE_LEARNING_PLAN = 'COMPLETE_LEARNING_PLAN',
}

export enum StreakActivityType {
  TEST_SUBMIT = 'TEST_SUBMIT',
  VOCAB_PRACTICE = 'VOCAB_PRACTICE',
  LESSON_PASS = 'LESSON_PASS',
}

export enum PostStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
}

export enum ReactType {
  LIKE = 'LIKE',
  LOVE = 'LOVE',
  HAHA = 'HAHA',
  WOW = 'WOW',
  SAD = 'SAD',
  ANGRY = 'ANGRY',
}

export enum EmailStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}

export enum EmailType {
  AUTO = 'AUTO',
  MANUAL = 'MANUAL',
}

export enum UserVocabularyStatus {
  LEARNING = 'learning',
  MASTERED = 'mastered',
}

export enum PermissionCode {
  USER_MANAGE = 'USER:MANAGE',
  ROLE_MANAGE = 'ROLE:MANAGE',
  EXAM_TYPE_MANAGE = 'EXAM_TYPE:MANAGE',
  EXAM_TYPE_LAYOUT_MANAGE = 'EXAM_TYPE:LAYOUT',
  EXAM_CATEGORY_MANAGE = 'EXAM_CATEGORY:MANAGE',
  EXAM_PART_MANAGE = 'EXAM_PART:MANAGE',
  SKILL_MANAGE = 'SKILL:MANAGE',
  PASSAGE_MANAGE = 'PASSAGE:MANAGE',
  PASSAGE_MEDIA_MANAGE = 'PASSAGE_MEDIA:MANAGE',
  ANSWER_VIEW = 'ANSWER:VIEW',
  ANSWER_MANAGE = 'ANSWER:MANAGE',
  TAG_MANAGE = 'TAG:MANAGE',
  SCORING_CONVERSION_MANAGE = 'SCORING_CONVERSION:MANAGE',
  QUESTION_COLLECTION_MANAGE = 'QUESTION_COLLECTION:MANAGE',
  QUESTION_MANAGE = 'QUESTION:MANAGE',
  MILESTONE_MANAGE = 'MILESTONE:MANAGE',
  RECOVERY_RESOURCE_MANAGE = 'RECOVERY_RESOURCE:MANAGE',
  TEST_MANAGE = 'TEST:MANAGE',
  TEST_MANAGE_PRICING = 'TEST:MANAGE_PRICING',
  ATTEMPT_MANAGE = 'ATTEMPT:MANAGE',
  EVALUATION_MANAGE = 'EVALUATION:MANAGE',
  POST_MODERATE = 'POST:MODERATE',
  POST_CATEGORY_MANAGE = 'POST_CATEGORY:MANAGE',
  VOCABULARY_MANAGE = 'VOCABULARY:MANAGE',
  CLASS_MANAGE = 'CLASS:MANAGE',
  QUEST_MANAGE = 'QUEST:MANAGE',
  COSMETIC_MANAGE = 'COSMETIC:MANAGE',
  COIN_MANAGE = 'COIN:MANAGE',
  STREAK_CONFIG_MANAGE = 'STREAK_CONFIG:MANAGE',
  CERTIFICATE_MANAGE = 'CERTIFICATE:MANAGE',
  AUDIT_VIEW = 'AUDIT:VIEW',
  DASHBOARD_VIEW = 'DASHBOARD:VIEW',
  EMAIL_MANAGE = 'EMAIL:MANAGE',
}
